---
## some comments that needs to be preserverd
## please when updating the file don't remove the content
apiVersion: v1
data:
  some-key: some-value
kind: ConfigMap
metadata:
  name: test-configmap
