apiVersion: acmp.corp/v1
kind: NamespaceRequest
metadata:
  name: tenant8
spec:
  cluster: dev01
  memory: 11
  new-property: new-value
---
apiVersion: v1
data:
  some-key: some-value
kind: ConfigMap
metadata:
  name: test-configmap
